travis:
  secure:
    BINSTAR_TOKEN: JRUNRZ/wPsNxE8r6Eok48nYl9tSHohidPtrkgUmnptmT4GQnoRVpxNDulTKQmAy3UlPa2hF/spVEgGMHveJFCqWLw+RGBTAxxOuQj0BvLLF+cdoIdRCG5szcBNYg5HPKbpZCTNzWI2vuKspWLDE/fLSs6jTse7zpCAL+xK9cxjEWhN900y6be0yzjfTQXqqug+z7YtBuWJCs9EQghgf1ZWoWqyWzlZLFfummWRHmFd1KYitd4LgmzPI9eMlPRTOOcpyOcCj4qz5xIwGMa3CvyGo/R1HCZ9bkDLoof/gBPr6p5O5fSMZilro/NwqyeKhw33HkwyX7NfF5U+bWIBhQrCk/CpXmNZQLSBIcp14yQcFli6rzJ8eTvFWSACzPac6x/cmJ+LLD3TcLrzO/rETGAvntItoz0/q3pm+cS8OooMPGmAiMDR8gFdkMdp3qmWLtTpc5nNaMo8YM+T46Tx4bo/N7kRzImw57r8ykwI3IXMlYy8uqUA5+tNJT7Nfx7aj6KnLIMCrZ4ChICtb9bXzkfFTDMF2QgzYtBuksdTQXUTyUmPTzocOJ3kjrpo41CsH/DaE96SaVZaJqjjUeHMxwuuaEa2gOHIZRuSQ9xL5DBENfmEoQRVgY8QYQt1HeneZiNm0kjqdsp1KUGQIG69NSXhl/Ogv0T6modAjal5DJ07c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
