travis:
  secure:
    BINSTAR_TOKEN: He9LmwCEGLykimOAr5CLjWgSpmpVBLN9MfGj8NxvVeCtre6C1OieZ5QjXPtWCqzFKbW7Hw0Qa44LXPCbiKztUVXRdd23laeeCqNjRrr5G8C0QdjSRcLHXzS9q/+ORrWUReo9SWse17DD1xiPwjT2lbBgmsvOtheaJAvYI9z9bcJt4xVltX6KDXViAyn09ONM6RnRGhQ4mlsp4xYxM0Vgx83Q2Us2oW8fdW3n4Zr6udw1QLftVmV457x4/+qI2XuwyrgPSymhc9hwgcwNW7ckfa3dRwKPBabwRgbm/IkwNszcM5GtCvYCRMVQhfSilc78Pmk8ZH8nj/iUNhHiiJEQQ5YURf9Xqaj5RDP6jiwCJTt1a6C1a/hUnDG4fRN/kZugg0EUAyzWfUZznWyp1muiko5Z2ss928hWuTorSYELq1UkCBTXWV9uiLt2BZFRVxE5VxWhVc+gt8AEK5BXOW6N/rXg2kcWycR5yU2fJTUnSsV8jeNkSbN8Mq6BOigkgJ+ldMk6UHxQ7gTB1W2KzIs6SkWcjnD7BRV6h8AS3VjdqOP4HQzlxNPs7yEObeL6jAITq3kSY/TAyhY96zOljf3dqqftKcgSCZtDpBjxCVrqqKugSxyxgBDMuwdr0leQHc80qmQBRhMzSVxbmUUK2w3w63jPHCOkcoGyVUARoWkCihc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
